name: Rust CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'

jobs:
  rust-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@1.59.0
        with:
          args: make rust-lint rust-test
